version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:latest
    volumes:
      - ./browsers.json:/etc/selenoid/browsers.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '4444:4444'

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    ports:
      - '8090:8080'
    command: --selenoid-uri http://selenoid:4444

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:5.2.1'
    ports:
      - '8091:80'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart

  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  opencart:
    image: docker.io/bitnami/opencart:4
    ports:
      - '8092:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=localhost
      # To change default opencart port next two lines should be uncommented
      # - APACHE_HTTP_PORT_NUMBER=8090
      # - OPENCART_EXTERNAL_HTTP_PORT_NUMBER=8090
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      # Password for user@default.com (login 'user') administrator account
      - OPENCART_PASSWORD=qwerty!123
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb

  tests:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./wait-for-it.sh:/selenium_tests/wait-for-it.sh
    command: ./wait-for-it.sh opencart 8080 pytest -v

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local